name: Continuous Integration Checks

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        toolchain: [stable]
        include:
          - toolchain: stable
            check-fmt: true

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Build on Rust stable
        run: cargo build --verbose --color always

      - name: Check formatting
        if: matrix.check-fmt
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check
