name: lnprototest testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t lnprototest-image -f docker/Dockerfile .

      - name: Run Docker Container
        run: |
          docker run --name lnprototest-container --rm lnprototest-image

      - name: Cleanup Docker
        if: always()
        run: |
          docker stop lnprototest-container || true
          docker rm lnprototest-container || true
